version: "3.9"
services:
  nginx:
    container_name: nginx
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/prisma-glue/meta/router/nginx
    ports:
      - 7001:7001
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/prisma-glue/meta/router/nginx/nginx.conf:/etc/nginx/nginx.conf
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/prisma-glue/frontend
    ports:
      - 3100:9000
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/prisma-glue:/gluestack
      - /gluestack/frontend/node_modules/
      - /gluestack/frontend/.next/
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/prisma-glue/frontend/.env.generated
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12
    ports:
      - 5433:5432
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/prisma-glue/backend/databases/postgres/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prisma_db
    healthcheck:
      test:
        - CMD-SHELL
        - psql -U postgres -d prisma_db
      interval: 10s
      timeout: 10s
      retries: 50
      start_period: 30s
